name: Create tagged release
on:
  push:
    tags:
      - v*.*.*

jobs:
  test:
    strategy:
      matrix:
        os: [ ubuntu-latest, windows-latest, macos-latest ]
        node: [ 12, 14, 16 ]
    runs-on: ${{matrix.os}}
    steps:
      - name: Set up Git repository
        uses: actions/checkout@v2
      - name: Set up node
        uses: actions/setup-node@v2
        with:
          node-version: ${{matrix.node}}
      - name: Setup Docker
        if: ${{matrix.os == 'ubuntu-latest'}}
        run: |
          docker pull s1hofmann/nut-ci:latest
          docker run -it -d --name nut-ci --shm-size 8gb --user $(id -u):$(id -g) -v ${PWD}:${PWD}:rw s1hofmann/nut-ci:latest bash
      - name: Install
        run: npm ci
      - name: Compile
        run: npm run compile
      - name: Init window e2e test subpackage
        run: npm --prefix e2e/window-test ci
      - name: Generate coverage report
        uses: GabrielBB/xvfb-action@v1
        with:
          run: npm test
      - name: Run Docker E2E tests
        if: ${{matrix.os == 'ubuntu-latest'}}
        run: docker exec nut-ci bash -c "bash $PWD/.build/build.sh ${PWD} ${{matrix.node}}"
      - name: Run Electron e2e test subpackage
        uses: GabrielBB/xvfb-action@v1
        with:
          run: npm --prefix e2e/electron-test cit

  deploy:
    needs:
      - test
    runs-on: ubuntu-latest
    steps:
      - name: Set up Git repository
        uses: actions/checkout@v2
      - name: Set up node
        uses: actions/setup-node@v2
        with:
          node-version: 14
          registry-url: 'https://registry.npmjs.org'
      - name: Install
        run: npm ci
      - name: Run typedoc
        run: npm run typedoc
      - name: Publish typedocs to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3.7.3
        with:
          deploy_key: ${{ secrets.API_DOC_DEPLOY_KEY }}
          external_repository: nut-tree/apidoc
          publish_dir: ./docs
      - name: Publish tagged release to npm
        run: npm publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
      - uses: actions/setup-node@v2
        with:
          registry-url: 'https://npm.pkg.github.com'
      - name: Publish tagged release to GPR
        run: npm publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}