name: Create tagged release
on:
  push:
    tags:
      - v*.*.*

jobs:
  test:
    strategy:
      matrix:
        os: [ ubuntu-latest, windows-latest, macos-latest ]
        node: [ 18 ]
    runs-on: ${{matrix.os}}
    env:
      NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
    steps:
      - name: Set up Git repository
        uses: actions/checkout@v3
      - name: Set up node
        uses: actions/setup-node@v3
        with:
          node-version: ${{matrix.node}}
          registry-url: https://registry.npmjs.org/
          token: ${{ secrets.NPM_TOKEN }}
      - name: Setup pnpm
        uses: pnpm/action-setup@v3.0.0
      - name: Install
        run: |
          pnpm whoami
          pnpm i
      - name: Compile
        run: npm run compile
      - name: Run tests
        uses: GabrielBB/xvfb-action@v1
        with:
          run: pnpm run coverage

  deploy:
    needs:
      - test
    runs-on: ubuntu-latest
    env:
      NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
    steps:
      - name: Set up Git repository
        uses: actions/checkout@v3
      - name: Set up node
        uses: actions/setup-node@v3
        with:
          node-version: 18
          registry-url: https://registry.npmjs.org/
          token: ${{ secrets.NPM_TOKEN }}
      - name: Setup pnpm
        uses: pnpm/action-setup@v3.0.0
      - name: Install
        run: |
          pnpm whoami
          pnpm i
      - name: Run typedoc
        run: pnpm run typedoc
      - name: Publish typedocs to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3.7.3
        with:
          deploy_key: ${{ secrets.API_DOC_DEPLOY_KEY }}
          external_repository: nut-tree/apidoc
          publish_dir: ./docs
      - name: Publish tagged release to npm
        run: pnpm run publish:release
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
